### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by estgold** [Firenox89/Shinobooru#1]
Hello,  I try to use this app,  but I have some problems with displaying images

> ![screenshot_20170215-032022](https://cloud.githubusercontent.com/assets/20031589/22955684/84996acc-f32e-11e6-8345-5db3b71eafaa.jpg)

![screenshot_20170215-032019](https://cloud.githubusercontent.com/assets/20031589/22955687/89b1e444-f32e-11e6-9790-b1d0867d93b5.jpg)
Gallery work nice,  but status bar is hidden
![screenshot_20170215-031927](https://cloud.githubusercontent.com/assets/20031589/22955702/a7117d24-f32e-11e6-9ac2-986f4ab98f02.jpg)
Device ASUS ZenFone 2 Android 6.0,  if You need more system info just ask

**Comment by Firenox89** [comment]
First thanks for testing :)
Easy thing first, the hidden statusbar was a setting I liked at first, but I will put it in again for the thumbnails.
Unfortunately I couldn't reproduce the rendering bugs on my devices. But this screenshots look so broken that it's probably some opengl related issue, maybe I find something when I google for it.

**Comment by Firenox89** [comment]
I pull the fragments into new files and gave proper ids to the ViewPagers, honestly I don't think this will fix this, but you could try anyway if you feel like it.

**Comment by estgold** [comment]
thank you,  I installed new version, but it not helped.  I will test your app at another device.

**Comment by Firenox89** [comment]
I added an alternate layout for viewing posts.
You can activate it in the settings, it does not use fragments so this could actually fix your problem.

**Comment by Firenox89** [comment]
Ok I got a new phone and can reproduce now...
